[Settings]
ID = "7b34978f-56c0-4f6e-b044-25fd2fb583ce"
[build]
  base    = ""
  publish = "dist/devstats-app"
  command = "ng build --prod  --c $ENV"
[context.production]
  environment = { ENV = "production" }
[context.deploy-preview]
  environment = { ENV = "" }
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
